// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqpvdiybogaqwxwefate.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcHZkaXlib2dhcXd4d2VmYXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTI0NjQsImV4cCI6MjA2MzAyODQ2NH0.6YvqoZd64uKuPmqKaAr1Xzw3K6KCWD0zyUoNXL2Z7X0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);